version: latest

architectures:
  linux-arm:
    name: armv6vfphLinux3.xgcc4.7.2
    libs:
      - libnddsc.so
      - libnddscore.so
      - librtiddsconnector.so
  linux-arm64:
    name: armv8Linux4.4gcc5.4.0
    libs:
      - libnddsc.so
      - libnddscore.so
      - librtiddsconnector.so
  linux-x64:
    name: x64Linux2.6gcc4.4.5
    libs:
      - libnddsc.so
      - libnddscore.so
      - librtiddsconnector.so
  osx-x64:
    name: x64Darwin17clang9.0
    libs:
      - libnddsc.dylib
      - libnddscore.dylib
      - librtiddsconnector.dylib
  win-x64:
    name: x64Win64VS2015
    libs:
      - nddsc.dll
      - nddscore.dll
      - rtiddsconnector.dll
      - vcruntime140.dll
